//===- GeneratableOpInterface.h - Generatable interface ---------*- C++ -*-===//
//
// Part of the LLVM Project, under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
//===----------------------------------------------------------------------===//
//
// This file implements the operation interface for generatable operations.
//
//===----------------------------------------------------------------------===//

#ifndef MLIR_INTERFACES_GENERATABLEOPINTERFACE_H
#define MLIR_INTERFACES_GENERATABLEOPINTERFACE_H

#include "mlir/IR/Builders.h"
#include "mlir/IR/PatternMatch.h"
#include "mlir/Tools/mlir-smith/MlirSmithMain.h"
#include <random>

namespace mlir {
class GeneratableOpInterface;

//===----------------------------------------------------------------------===//
// Configuration options for the generator
//===----------------------------------------------------------------------===//

struct GeneratorOpBuilderConfig {
  friend LogicalResult mlir::mlirSmithMain(int argc, char **argv,
                                           DialectRegistry &registry);

private:
  unsigned Seed;
  unsigned RegionDepthLimit;
  unsigned BlockLengthLimit;
  unsigned DefaultProb;
  llvm::StringMap<unsigned> OpProbs;

public:
  /// Initial seed of the random number generator.
  unsigned seed() { return Seed; }
  /// Limit for the depth of nested regions.
  unsigned regionDepthLimit() { return RegionDepthLimit; }
  /// Limit for the number of operations generated by generateBlock().
  unsigned blockLengthLimit() { return BlockLengthLimit; }
  /// Default probability for generating an operation.
  unsigned defaultProb() { return DefaultProb; }
  /// Probabilities for generating operations.
  llvm::StringMap<unsigned> opProbs() { return OpProbs; }
  /// Returns the probability of an operation if it's set, otherwise the default
  /// probability.
  unsigned getProb(StringRef name) {
    return OpProbs.contains(name) ? OpProbs[name] : DefaultProb;
  }

  LogicalResult
  loadFromFileContent(StringRef configFileContent,
                      std::string *errorMessage = (std::string *)nullptr) {
    // Clear previous default values
    OpProbs = {};

    std::istringstream input(configFileContent.str());
    std::string line;
    unsigned lineNr = 0;

    while (std::getline(input, line)) {
      if (line.empty())
        continue;
      std::istringstream lineStream(line);
      std::string key;
      char equalsSign;
      unsigned value;
      lineNr++;

      if (lineStream >> key >> equalsSign >> value && equalsSign == '=') {
        if (key == "seed")
          Seed = value;
        else if (key == "regionDepthLimit")
          RegionDepthLimit = value;
        else if (key == "blockLengthLimit")
          BlockLengthLimit = value;
        else if (key == "defaultProb")
          DefaultProb = value;
        else
          OpProbs[key] = value;
      } else {
        if (errorMessage)
          *errorMessage =
              "failed to parse config file at line " + std::to_string(lineNr);
        return failure();
      }
    }

    return success();
  }

  void loadDefaultValues(MLIRContext *ctx) {
    Seed = time(0);
    RegionDepthLimit = 3;
    BlockLengthLimit = 20;
    DefaultProb = 1;
    OpProbs = {};

    for (RegisteredOperationName ron : ctx->getRegisteredOperations())
      if (ron.hasInterface<GeneratableOpInterface>())
        OpProbs[ron.getStringRef()] = DefaultProb;
  }

  void dumpConfig(llvm::raw_ostream &os) {
    os << "seed = " << Seed << "\n";
    os << "regionDepthLimit = " << RegionDepthLimit << "\n";
    os << "blockLengthLimit = " << BlockLengthLimit << "\n";
    os << "defaultProb = " << DefaultProb << "\n";

    // Sort OpProbs for nicer print.
    std::vector<llvm::StringMapEntry<unsigned> *> vec;
    vec.reserve(OpProbs.size());
    for (auto &pair : OpProbs)
      vec.push_back(&pair);

    std::sort(vec.begin(), vec.end(),
              [](const llvm::StringMapEntry<unsigned> *a,
                 const llvm::StringMapEntry<unsigned> *b) {
                return a->getKey().compare(b->getKey()) < 0;
              });

    for (auto *entry : vec)
      os << entry->getKey() << " = " << entry->getValue() << "\n";
  }
};

//===----------------------------------------------------------------------===//
// OpBuilder with utilities for IR generation
//===----------------------------------------------------------------------===//

/// This class implements a builder for use in generation functions. It
/// extends the base OpBuilder and provides utility functions to generate
/// common structures and to sample from a configured distribution.
class GeneratorOpBuilder final : public OpBuilder {
public:
  explicit GeneratorOpBuilder(MLIRContext *ctxt,
                              GeneratorOpBuilderConfig generatorConfig);

  //===--------------------------------------------------------------------===//
  // State Management
  //===--------------------------------------------------------------------===//

  /// This class represents a saved snapshot of an operation.
  class Snapshot {
  public:
    Snapshot() = default;
    Snapshot(OpBuilder::InsertPoint ip) : ip(ip) {}

    OpBuilder::InsertPoint getInsertionPoint() { return ip; }

  private:
    OpBuilder::InsertPoint ip;
  };

  /// Takes a snapshot of the current state.
  Snapshot takeSnapshot();

  /// Rolls back to the provided snapshot.
  void rollback(Snapshot snapshot);

  //===--------------------------------------------------------------------===//
  // Operation Creation
  //===--------------------------------------------------------------------===//

  /// Checks if the given OperationState adheres to the generator constraints.
  bool canCreate(const OperationState &state);

  /// Creates an operation given the fields represented as an OperationState and
  /// enforces generator constraints.
  Operation *create(const OperationState &state);

  //===--------------------------------------------------------------------===//
  // Samplers
  //===--------------------------------------------------------------------===//

  /// Samples from a vector of choices. If no probability vector is provided,
  /// it samples using a uniform distribution.
  template <typename T>
  llvm::Optional<T> sample(llvm::SmallVector<T> choices,
                           llvm::SmallVector<unsigned> probs = {});

  /// Returns a random number between 0 and max (inclusive) using uniform
  /// distribution.
  unsigned sampleUniform(int32_t max);

  /// Returns a random boolean.
  bool sampleBool();

  /// Returns a random number using a normal distribution around zero.
  int8_t sampleNumberInt8();

  /// Returns a random number using a normal distribution around zero.
  int16_t sampleNumberInt16();

  /// Returns a random number using a normal distribution around zero.
  int32_t sampleNumberInt32();

  /// Returns a random number using a normal distribution around zero.
  int64_t sampleNumberInt64();

  /// Returns a random number using a normal distribution around zero.
  float_t sampleNumberFloat();

  /// Returns a random number using a normal distribution around zero.
  double_t sampleNumberDouble();

  /// Samples from a geometric distribution of available types in the current
  /// position.
  llvm::SmallVector<Type> sampleTypes(int32_t min = 0);

  /// Randomly chooses a generated value of the given type, if one exists.
  llvm::Optional<Value> sampleValueOfType(Type t);

  //===--------------------------------------------------------------------===//
  // Generators
  //===--------------------------------------------------------------------===//

  /// Randomly generates an operation in the current position.
  // FIXME: This doesn't differentiate between ops not provided and an empty
  // list.
  LogicalResult
  generateOperation(llvm::SmallVector<RegisteredOperationName> ops = {});

  /// Randomly generates a terminator operation in the current position.
  LogicalResult generateTerminator();

  /// Fills the current block with operations.
  LogicalResult generateBlock(bool ensureTerminator = false);

private:
  /// Utility function to generate an operation.
  LogicalResult generate(RegisteredOperationName ron);

  /// Returns a random number using a normal distribution around zero. This
  /// function combines all specialized functions.
  template <typename T>
  T sampleNumber();

  /// Random number generator.
  std::mt19937 rngGen;

  /// The configuration used for IR generation.
  GeneratorOpBuilderConfig generatorConfig;

  /// All operations that can be generated.
  llvm::SmallVector<RegisteredOperationName> availableOps = {};

  /// If set, forces operations to have the specified return type.
  llvm::Optional<Type> requiredReturnType;

  /// Allows bypassing the block length limit to ensure that terminators can be
  /// generated.
  bool bypassBlockLengthLimit = false;
};

} // namespace mlir

//===----------------------------------------------------------------------===//
// Generated Interface Declarations
//===----------------------------------------------------------------------===//

#include "mlir/Interfaces/GeneratableOpInterface.h.inc"

#endif // MLIR_INTERFACES_GENERATABLEOPINTERFACE_H
